/*
======================= RANDOM CLASS =======================

Definition:
- The Random class is used to generate pseudo-random values.
- It belongs to the java.util package.

Import : import java.util.Random;

Create a Random Object : Random objectName = new Random();
Random r = new Random();

---------------------------------------------------------------
1. Random Integer - Generates a random integer.
---------------------------------------------------------------

Method : r.nextInt()

Default Range :  -2,147,483,648 to 2,147,483,647
(Integer.MIN_VALUE to Integer.MAX_VALUE)

Custom Range:
min (inclusive) to maxExclusive (exclusive)

Example:
r.nextInt(1, 7)

Possible Output:
1, 2, 3, 4, 5, 6

Useful for:
- Dice rolls
- OTP generation
- Random IDs
- Games

---------------------------------------------------------------
2. Random Double - Generates a random decimal number.
---------------------------------------------------------------

Method : r.nextDouble()

Default Range : 0.0 (inclusive) to 1.0 (exclusive)

Custom Range : 
r.nextDouble(min, maxExclusive)

Example:
r.nextDouble(1.5, 5.5)

Possible Output:
2.37
4.91
1.86

Useful for:
- Probability
- Simulations
- Random decimal values

---------------------------------------------------------------
3. Random Boolean - Generates either true or false.
---------------------------------------------------------------

Method:
r.nextBoolean()

Possible Output:
true
false

Useful for:
- Coin Toss
- Yes/No decisions
- Random events

---------------------------------------------------------------
Common Examples
---------------------------------------------------------------

Dice Roll:
int dice = r.nextInt(1, 7);

Coin Toss:
boolean coin = r.nextBoolean();

Password Generator:
Random characters and numbers.

Lottery Number Generator.

Game Development:
Random enemy spawn
Random rewards
Random map generation

---------------------------------------------------------------
Important Notes
---------------------------------------------------------------
1. Import java.util.Random before using the Random class.

2. Create only one Random object and reuse it.

3. Random numbers are pseudo-random, meaning they are
   generated by an algorithm and are suitable for most
   applications but not for cryptographic security.

===============================================================
*/
package A1_JavaBasics;

import java.util.Random;

public class A6_random {
    public static void main(String[] args) {
        System.out.println("Random Number\n");
        Random r = new Random();        // Create a Rnadom Object - "r", or any name you want.


        // Random Int
        int num;
        num = r.nextInt();      // default range => -2 billion to +2 billion
        System.out.println("random number : "+num+ "\n");
        
        // Random Double
        double decimal;
        decimal = r.nextDouble();      // default range => 0 to 1
        System.out.println("random decimal : "+decimal+ "\n");
        
        // Random boolean
        boolean isStudent;
        isStudent = r.nextBoolean();      // default range => 0 to 1
        System.out.println("random boolean value : "+isStudent+ "\n");



        // A dice throw 
        int dice;
        dice = r.nextInt(1,7);
        System.out.println("dice throw : "+dice+ "\n");


        // A coin toss
        boolean coin = r.nextBoolean();
        if (coin) {
            System.out.println("coin toss : HEADS\n");
        }
        else {
            System.out.println("coin toss : TAILS\n");
        }
        

    }
    
}
